#%RAML 1.0
title: Commission Leasing
baseUri: http://localhost:8081/api
version: 1.0

/commission-leasing-requests:
  post:
  /{clid}:
    get:
    /proposal:
      post:
      get:
      /commission-leasing-order:
        post:
/commission-leasing-orders/{cloid}:
  get:
  /cancellation:
    post:
    get:
    /confirmation:
      post:
  /leasing:
    post:
    get:
    /confirmation:
      post:
  /agency-fee-payment:
    post:
    get:
    /confirmation:
      post:
