#%RAML 1.0
title: Commission Tenanting
baseUri: http://localhost:8081/api
version: 1.0

/commission-tenanting-requests:
  post:
  /{ctid}:
    get:
    /proposal:
      post:
      get:
      /commission-tenanting-order:
        post:
/commission-tenanting-orders/{ctoid}:
  get:
  /agency-fee-payment:
    post:
    get:
    /confirmation:
      post:
  /tenanting:
    post:
    get:
    /confirmation:
      post:
  /views:
    post:
    /vid:
      get:
      /confirmation:
        post:
