#%RAML 1.0
title: Payment API
baseUri: http://localhost:8081/api
version: 1.0

/payment-services:
  post:
    description: 签订支付服务合同
    headers:
      userId: 
        type: string
        description: 用户ID
        required: true
    responses:
        200:
  /{psid}/payments:
    uriParameters: 
      psid: 
        description: 支付合同ID
    post:
      description: 请求支付
      headers:
        userId: 
          type: string
          description: 用户ID
          required: true
      responses:
          200:
    /{pid}:
      uriParameters: 
        pid: 
          description: 支付请求ID 
      get:
        description: 查看支付请求
        headers:
          userId: 
            type: string
            description: 用户ID
            required: true
        responses:
            200: 
      /confirmation:
        post:
          description: 支付确认
          headers:
            userId: 
              type: string
              description: 用户ID
              required: true
          responses:
              200: