#%RAML 1.0
title: Rental API
baseUri: http://localhost:8081/api
version: 1.0

/Rentals:
  post:
    description: 签订房屋租凭合同
    headers:
      userId: 
        type: string
        description: 用户ID
        required: true
    responses:
        200:
  /{rid}:
    uriParameters: 
      rid: 
        description: 租凭合同ID
    get:
      description: 查看房屋租凭合同
      headers:
        userId: 
          type: string
          description: 用户ID
          required: true
      responses:
        200: